export default (<[string, boolean][]>[
  ["", true],
  ["asdasdasd", true],
  ["15125125", true],
  ["qw4bqwb4qw4", true],
  [":AW_EW_EWA_%§", true],
  [null, true],
  [{}, true],
  [{ a: 2 }, true],
  [[2, 4, 56], true],
  [["dsad"], true],
  [undefined, true],
  [4, true],
  [5.4, true],
  [NaN, true],
  [false, true],
  [true, true],
]).map((tuple) => ({
  value: tuple[0],
  expected: tuple[1],
}));
