export default (<[string, boolean][]>[
  ["", false],
  ["asdasdasd", false],
  ["15125125", false],
  ["qw4bqwb4qw4", false],
  [":AW_EW_EWA_%§", false],
  [null, true],
  [{}, false],
  [{ a: 2 }, false],
  [{ a: "test" }, false],
  [{ a: "test", b: 2 }, false],
  [[2, 4, 56], false],
  [[2, 4, 56, "test"], false],
  [["dsad"], true],
  [undefined, false],
  [4, false],
  [5.4, false],
  [NaN, false],
  [false, false],
  [true, false],
]).map((tuple) => ({
  value: tuple[0],
  expected: tuple[1],
}));
