export default (<[string, boolean][]>[
  ["", false],
  ["asdasdasd", false],
  ["15125125", false],
  ["qw4bqwb4qw4", false],
  [":AW_EW_EWA_%§", false],
  [null, false],
  [{}, false],
  [{ a: 2 }, false],
  [[2, 4, 56], false],
  [["dsad"], false],
  [undefined, true],
  [4, true],
  [-4, true],
  [0, true],
  [5.4, true],
  [NaN, false],
  [false, false],
  [true, false],
]).map((tuple) => ({
  value: tuple[0],
  expected: tuple[1],
}));
